name: Call Deploy Action

on:
  push:
    branches:
      - main

jobs:
  Layer_deploy:
    strategy:
      matrix:
        layer: [pynacl_layer, requests_layer]
        include:
          - layer: pynacl_layer
            path: ./layers/pynacl
          - layer: requests_layer
            path: ./layers/requests

    uses: junah201/GaeBari-Bot/.github/workflows/layer.yml@main
    with:
      file_path: ${{ matrix.path }}
      layer_name: ${{ matrix.layer }}
    secrets: inherit

  Lambda_deploy:
    strategy:
      matrix:
        lambda: [event_handler]
        include:
          - lambda: event_handler
            path: ./lambdas/event_handler

    uses: junah201/GaeBari-Bot/.github/workflows/lambda.yml@main
    with:
      file_path: ${{ matrix.path }}
      lambda_name: ${{ matrix.lambda }}
    secrets: inherit
